.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
'''   \*(M", \*(S", \*(N" and \*(T" are the equivalent of
'''   \*(L" and \*(R", except that they are used on ".xx" lines,
'''   such as .IP and .SH, which do another additional levels of
'''   double-quote interpretation
.ds M" """
.ds S" """
.ds N" """""
.ds T" """""
.ds L' '
.ds R' '
.ds M' '
.ds S' '
.ds N' '
.ds T' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds M" ``
.ds S" ''
.ds N" ``
.ds T" ''
.ds L' `
.ds R' '
.ds M' `
.ds S' '
.ds N' `
.ds T' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH PERLFAQ 1 "perl 5.005, patch 03" "27/Mar/1999" "Perl Programmers Reference Guide"
.UC
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
perlfaq \- frequently asked questions about Perl ($Date: 1999/01/08 05:54:52 $)
.SH "DESCRIPTION"
This document is structured into the following sections:
.Ip "perlfaq: Structural overview of the \s-1FAQ\s0." 5
This document.
.Ip "the \fIperlfaq1\fR manpage: General Questions About Perl" 5
Very general, high-level information about Perl.
.Ip "\(bu What is Perl?" 9
.Ip "\(bu Who supports Perl?  Who develops it?  Why is it free?" 9
.Ip "\(bu Which version of Perl should I use?" 9
.Ip "\(bu What are perl4 and perl5?" 9
.Ip "\(bu What is perl6?" 9
.Ip "\(bu How stable is Perl?" 9
.Ip "\(bu Is Perl difficult to learn?" 9
.Ip "\(bu How does Perl compare with other languages like Java, Python, \s-1REXX\s0, Scheme, or Tcl?" 9
.Ip "\(bu Can I do [task] in Perl?" 9
.Ip "\(bu When shouldn't I program in Perl?" 9
.Ip "\(bu What's the difference between \*(N"perl\*(T" and \*(N"Perl\*(T"?" 9
.Ip "\(bu Is it a Perl program or a Perl script?" 9
.Ip "\(bu What is a \s-1JAPH\s0?" 9
.Ip "\(bu Where can I get a list of Larry Wall witticisms?" 9
.Ip "\(bu How can I convince my sysadmin/supervisor/employees to use version (5/5.005/Perl instead of some other language)?" 9
.Ip "the \fIperlfaq2\fR manpage: Obtaining and Learning about Perl" 5
Where to find source and documentation to Perl, support,
and related matters.
.Ip "\(bu What machines support Perl?  Where do I get it?" 9
.Ip "\(bu How can I get a binary version of Perl?" 9
.Ip "\(bu I don't have a C compiler on my system.  How can I compile perl?" 9
.Ip "\(bu I copied the Perl binary from one machine to another, but scripts don't work." 9
.Ip "\(bu I grabbed the sources and tried to compile but gdbm/dynamic loading/malloc/linking/... failed.  How do I make it work?" 9
.Ip "\(bu What modules and extensions are available for Perl?  What is \s-1CPAN\s0?  What does \s-1CPAN/\s0src/... mean?" 9
.Ip "\(bu Is there an \s-1ISO\s0 or \s-1ANSI\s0 certified version of Perl?" 9
.Ip "\(bu Where can I get information on Perl?" 9
.Ip "\(bu What are the Perl newsgroups on \s-1USENET\s0?  Where do I post questions?" 9
.Ip "\(bu Where should I post source code?" 9
.Ip "\(bu Perl Books" 9
.Ip "\(bu Perl in Magazines" 9
.Ip "\(bu Perl on the Net: \s-1FTP\s0 and \s-1WWW\s0 Access" 9
.Ip "\(bu What mailing lists are there for perl?" 9
.Ip "\(bu Archives of comp.lang.perl.misc" 9
.Ip "\(bu Where can I buy a commercial version of Perl?" 9
.Ip "\(bu Where do I send bug reports?" 9
.Ip "\(bu What is perl.com?  " 9
.Ip "the \fIperlfaq3\fR manpage: Programming Tools" 5
Programmer tools and programming support.
.Ip "\(bu How do I do (anything)?" 9
.Ip "\(bu How can I use Perl interactively?" 9
.Ip "\(bu Is there a Perl shell?" 9
.Ip "\(bu How do I debug my Perl programs?" 9
.Ip "\(bu How do I profile my Perl programs?" 9
.Ip "\(bu How do I cross-reference my Perl programs?" 9
.Ip "\(bu Is there a pretty-printer (formatter) for Perl?" 9
.Ip "\(bu Is there a ctags for Perl?" 9
.Ip "\(bu Is there an \s-1IDE\s0 or Windows Perl Editor?" 9
.Ip "\(bu Where can I get Perl macros for vi?" 9
.Ip "\(bu Where can I get perl-mode for emacs?" 9
.Ip "\(bu How can I use curses with Perl?" 9
.Ip "\(bu How can I use X or Tk with Perl?" 9
.Ip "\(bu How can I generate simple menus without using \s-1CGI\s0 or Tk?" 9
.Ip "\(bu What is undump?" 9
.Ip "\(bu How can I make my Perl program run faster?" 9
.Ip "\(bu How can I make my Perl program take less memory?" 9
.Ip "\(bu Is it unsafe to return a pointer to local data?" 9
.Ip "\(bu How can I free an array or hash so my program shrinks?" 9
.Ip "\(bu How can I make my \s-1CGI\s0 script more efficient?" 9
.Ip "\(bu How can I hide the source for my Perl program?" 9
.Ip "\(bu How can I compile my Perl program into byte code or C?" 9
.Ip "\(bu How can I compile Perl into Java?" 9
.Ip "\(bu How can I get \f(CW#!perl\fR to work on [\s-1MS\s0\-\s-1DOS\s0,\s-1NT\s0,...]?" 9
.Ip "\(bu Can I write useful perl programs on the command line?" 9
.Ip "\(bu Why don't perl one-liners work on my \s-1DOS/\s0Mac/\s-1VMS\s0 system?" 9
.Ip "\(bu Where can I learn about \s-1CGI\s0 or Web programming in Perl?" 9
.Ip "\(bu Where can I learn about object-oriented Perl programming?" 9
.Ip "\(bu Where can I learn about linking C with Perl? [h2xs, xsubpp]" 9
.Ip "\(bu I've read perlembed, perlguts, etc., but I can't embed perl in my C program, what am I doing wrong?" 9
.Ip "\(bu When I tried to run my script, I got this message. What does it mean?" 9
.Ip "\(bu What's MakeMaker?" 9
.Ip "the \fIperlfaq4\fR manpage: Data Manipulation" 5
Manipulating numbers, dates, strings, arrays, hashes, and
miscellaneous data issues.
.Ip "\(bu Why am I getting long decimals (eg, 19.9499999999999) instead of the numbers I should be getting (eg, 19.95)?" 9
.Ip "\(bu Why isn't my octal data interpreted correctly?" 9
.Ip "\(bu Does Perl have a round() function?  What about ceil() and floor()?  Trig functions?" 9
.Ip "\(bu How do I convert bits into ints?" 9
.Ip "\(bu Why doesn't & work the way I want it to?" 9
.Ip "\(bu How do I multiply matrices?" 9
.Ip "\(bu How do I perform an operation on a series of integers?" 9
.Ip "\(bu How can I output Roman numerals?" 9
.Ip "\(bu Why aren't my random numbers random?" 9
.Ip "\(bu How do I find the week-of-the-year/day-of-the-year?" 9
.Ip "\(bu How can I compare two dates and find the difference?" 9
.Ip "\(bu How can I take a string and turn it into epoch seconds?" 9
.Ip "\(bu How can I find the Julian Day?" 9
.Ip "\(bu How do I find yesterday's date?" 9
.Ip "\(bu Does Perl have a year 2000 problem?  Is Perl Y2K compliant?" 9
.Ip "\(bu How do I validate input?" 9
.Ip "\(bu How do I unescape a string?" 9
.Ip "\(bu How do I remove consecutive pairs of characters?" 9
.Ip "\(bu How do I expand function calls in a string?" 9
.Ip "\(bu How do I find matching/nesting anything?" 9
.Ip "\(bu How do I reverse a string?" 9
.Ip "\(bu How do I expand tabs in a string?" 9
.Ip "\(bu How do I reformat a paragraph?" 9
.Ip "\(bu How can I access/change the first N letters of a string?" 9
.Ip "\(bu How do I change the Nth occurrence of something?" 9
.Ip "\(bu How can I count the number of occurrences of a substring within a string?" 9
.Ip "\(bu How do I capitalize all the words on one line?" 9
.Ip "\(bu How can I split a [character] delimited string except when inside [character]? (Comma-separated files)" 9
.Ip "\(bu How do I strip blank space from the beginning/end of a string?" 9
.Ip "\(bu How do I pad a string with blanks or pad a number with zeroes?" 9
.Ip "\(bu How do I extract selected columns from a string?" 9
.Ip "\(bu How do I find the soundex value of a string?" 9
.Ip "\(bu How can I expand variables in text strings?" 9
.Ip "\(bu What's wrong with always quoting \*(N"$vars\*(T"?" 9
.Ip "\(bu Why don't my <<\s-1HERE\s0 documents work?" 9
.Ip "\(bu What is the difference between a list and an array?" 9
.Ip "\(bu What is the difference between $array[1] and @array[1]?" 9
.Ip "\(bu How can I extract just the unique elements of an array?" 9
.Ip "\(bu How can I tell whether a list or array contains a certain element?" 9
.Ip "\(bu How do I compute the difference of two arrays?  How do I compute the intersection of two arrays?" 9
.Ip "\(bu How do I test whether two arrays or hashes are equal?" 9
.Ip "\(bu How do I find the first array element for which a condition is true?" 9
.Ip "\(bu How do I handle linked lists?" 9
.Ip "\(bu How do I handle circular lists?" 9
.Ip "\(bu How do I shuffle an array randomly?" 9
.Ip "\(bu How do I process/modify each element of an array?" 9
.Ip "\(bu How do I select a random element from an array?" 9
.Ip "\(bu How do I permute N elements of a list?" 9
.Ip "\(bu How do I sort an array by (anything)?" 9
.Ip "\(bu How do I manipulate arrays of bits?" 9
.Ip "\(bu Why does defined() return true on empty arrays and hashes?" 9
.Ip "\(bu How do I process an entire hash?" 9
.Ip "\(bu What happens if I add or remove keys from a hash while iterating over it?" 9
.Ip "\(bu How do I look up a hash element by value?" 9
.Ip "\(bu How can I know how many entries are in a hash?" 9
.Ip "\(bu How do I sort a hash (optionally by value instead of key)?" 9
.Ip "\(bu How can I always keep my hash sorted?" 9
.Ip "\(bu What's the difference between \*(N"delete\*(T" and \*(N"undef\*(T" with hashes?" 9
.Ip "\(bu Why don't my tied hashes make the defined/exists distinction?" 9
.Ip "\(bu How do I reset an each() operation part-way through?" 9
.Ip "\(bu How can I get the unique keys from two hashes?" 9
.Ip "\(bu How can I store a multidimensional array in a \s-1DBM\s0 file?" 9
.Ip "\(bu How can I make my hash remember the order I put elements into it?" 9
.Ip "\(bu Why does passing a subroutine an undefined element in a hash create it?" 9
.Ip "\(bu How can I make the Perl equivalent of a C structure/\*(C+ class/hash or array of hashes or arrays?" 9
.Ip "\(bu How can I use a reference as a hash key?" 9
.Ip "\(bu How do I handle binary data correctly?" 9
.Ip "\(bu How do I determine whether a scalar is a number/whole/integer/float?" 9
.Ip "\(bu How do I keep persistent data across program calls?" 9
.Ip "\(bu How do I print out or copy a recursive data structure?" 9
.Ip "\(bu How do I define methods for every class/object?" 9
.Ip "\(bu How do I verify a credit card checksum?" 9
.Ip "\(bu How do I pack arrays of doubles or floats for \s-1XS\s0 code?" 9
.Ip "the \fIperlfaq5\fR manpage: Files and Formats" 5
I/O and the \*(L"f\*(R" issues: filehandles, flushing, formats and footers.
.Ip "\(bu How do I flush/unbuffer an output filehandle?  Why must I do this?" 9
.Ip "\(bu How do I change one line in a file/delete a line in a file/insert a line in the middle of a file/append to the beginning of a file?" 9
.Ip "\(bu How do I count the number of lines in a file?" 9
.Ip "\(bu How do I make a temporary file name?" 9
.Ip "\(bu How can I manipulate fixed-record-length files?" 9
.Ip "\(bu How can I make a filehandle local to a subroutine?  How do I pass filehandles between subroutines?  How do I make an array of filehandles?" 9
.Ip "\(bu How can I use a filehandle indirectly?" 9
.Ip "\(bu How can I set up a footer format to be used with write()?" 9
.Ip "\(bu How can I write() into a string?" 9
.Ip "\(bu How can I output my numbers with commas added?" 9
.Ip "\(bu How can I translate tildes (~) in a filename?" 9
.Ip "\(bu How come when I open a file read-write it wipes it out?" 9
.Ip "\(bu Why do I sometimes get an \*(N"Argument list too long\*(T" when I use <*>?" 9
.Ip "\(bu Is there a leak/bug in glob()?" 9
.Ip "\(bu How can I open a file with a leading \*(N">\*(T" or trailing blanks?" 9
.Ip "\(bu How can I reliably rename a file?" 9
.Ip "\(bu How can I lock a file?" 9
.Ip "\(bu Why can't I just open(\s-1FH\s0, \*(N">file.lock"")?" 9
.Ip "\(bu I still don't get locking.  I just want to increment the number in the file.  How can I do this?" 9
.Ip "\(bu How do I randomly update a binary file?" 9
.Ip "\(bu How do I get a file's timestamp in perl?" 9
.Ip "\(bu How do I set a file's timestamp in perl?" 9
.Ip "\(bu How do I print to more than one file at once?" 9
.Ip "\(bu How can I read in a file by paragraphs?" 9
.Ip "\(bu How can I read a single character from a file?  From the keyboard?" 9
.Ip "\(bu How can I tell whether there's a character waiting on a filehandle?" 9
.Ip "\(bu How do I do a \f(CWtail -f\fR in perl?" 9
.Ip "\(bu How do I dup() a filehandle in Perl?" 9
.Ip "\(bu How do I close a file descriptor by number?" 9
.Ip "\(bu Why can't I use \*(N"C:\etemp\efoo\*(T" in \s-1DOS\s0 paths?  What doesn't `C:\etemp\efoo.exe` work?" 9
.Ip "\(bu Why doesn't glob'*.*' get all the files?" 9
.Ip "\(bu Why does Perl let me delete read-only files?  Why does \f(CW-i\fR clobber protected files?  Isn't this a bug in Perl?" 9
.Ip "\(bu How do I select a random line from a file?" 9
.Ip "\(bu Why do I get weird spaces when I print an array of lines?" 9
.Ip "the \fIperlfaq6\fR manpage: Regexps" 5
Pattern matching and regular expressions.
.Ip "\(bu How can I hope to use regular expressions without creating illegible and unmaintainable code?" 9
.Ip "\(bu I'm having trouble matching over more than one line.  What's wrong?" 9
.Ip "\(bu How can I pull out lines between two patterns that are themselves on different lines?" 9
.Ip "\(bu I put a regular expression into $/ but it didn't work. What's wrong?" 9
.Ip "\(bu How do I substitute case insensitively on the \s-1LHS\s0, but preserving case on the \s-1RHS\s0?" 9
.Ip "\(bu How can I make \f(CW\ew\fR match national character sets?" 9
.Ip "\(bu How can I match a locale-smart version of \f(CW/[a-zA-Z]/\fR?" 9
.Ip "\(bu How can I quote a variable to use in a regexp?" 9
.Ip "\(bu What is \f(CW/o\fR really for?" 9
.Ip "\(bu How do I use a regular expression to strip C style comments from a file?" 9
.Ip "\(bu Can I use Perl regular expressions to match balanced text?" 9
.Ip "\(bu What does it mean that regexps are greedy?  How can I get around it?" 9
.Ip "\(bu How do I process each word on each line?" 9
.Ip "\(bu How can I print out a word-frequency or line-frequency summary?" 9
.Ip "\(bu How can I do approximate matching?" 9
.Ip "\(bu How do I efficiently match many regular expressions at once?" 9
.Ip "\(bu Why don't word-boundary searches with \f(CW\eb\fR work for me?" 9
.Ip "\(bu Why does using $&, $`, or $\*(T' slow my program down?" 9
.Ip "\(bu What good is \f(CW\eG\fR in a regular expression?" 9
.Ip "\(bu Are Perl regexps DFAs or NFAs?  Are they \s-1POSIX\s0 compliant?" 9
.Ip "\(bu What's wrong with using grep or map in a void context?" 9
.Ip "\(bu How can I match strings with multibyte characters?" 9
.Ip "\(bu How do I match a pattern that is supplied by the user?" 9
.Ip "the \fIperlfaq7\fR manpage: General Perl Language Issues" 5
General Perl language issues that don't clearly fit into any of the
other sections.
.Ip "\(bu Can I get a \s-1BNF/\s0yacc/\s-1RE\s0 for the Perl language?" 9
.Ip "\(bu What are all these $@%* punctuation signs, and how do I know when to use them?" 9
.Ip "\(bu Do I always/never have to quote my strings or use semicolons and commas?" 9
.Ip "\(bu How do I skip some return values?" 9
.Ip "\(bu How do I temporarily block warnings?" 9
.Ip "\(bu What's an extension?" 9
.Ip "\(bu Why do Perl operators have different precedence than C operators?" 9
.Ip "\(bu How do I declare/create a structure?" 9
.Ip "\(bu How do I create a module?" 9
.Ip "\(bu How do I create a class?" 9
.Ip "\(bu How can I tell if a variable is tainted?" 9
.Ip "\(bu What's a closure?" 9
.Ip "\(bu What is variable suicide and how can I prevent it?" 9
.Ip "\(bu How can I pass/return a {Function, FileHandle, Array, Hash, Method, Regexp}?" 9
.Ip "\(bu How do I create a static variable?" 9
.Ip "\(bu What's the difference between dynamic and lexical (static) scoping?  Between local() and my()?" 9
.Ip "\(bu How can I access a dynamic variable while a similarly named lexical is in scope?" 9
.Ip "\(bu What's the difference between deep and shallow binding?" 9
.Ip "\(bu Why doesn't \*(N"my($foo) = <\s-1FILE\s0>;\*(T" work right?" 9
.Ip "\(bu How do I redefine a builtin function, operator, or method?" 9
.Ip "\(bu What's the difference between calling a function as &foo and foo()?" 9
.Ip "\(bu How do I create a switch or case statement?" 9
.Ip "\(bu How can I catch accesses to undefined variables/functions/methods?" 9
.Ip "\(bu Why can't a method included in this same file be found?" 9
.Ip "\(bu How can I find out my current package?" 9
.Ip "\(bu How can I comment out a large block of perl code?" 9
.Ip "\(bu How do I clear a package?" 9
.Ip "the \fIperlfaq8\fR manpage: System Interaction" 5
Interprocess communication (\s-1IPC\s0), control over the user-interface
(keyboard, screen and pointing devices).
.Ip "\(bu How do I find out which operating system I'm running under?" 9
.Ip "\(bu How come exec() doesn't return?" 9
.Ip "\(bu How do I do fancy stuff with the keyboard/screen/mouse?" 9
.Ip "\(bu How do I print something out in color?" 9
.Ip "\(bu How do I read just one key without waiting for a return key?" 9
.Ip "\(bu How do I check whether input is ready on the keyboard?" 9
.Ip "\(bu How do I clear the screen?" 9
.Ip "\(bu How do I get the screen size?" 9
.Ip "\(bu How do I ask the user for a password?" 9
.Ip "\(bu How do I read and write the serial port?" 9
.Ip "\(bu How do I decode encrypted password files?" 9
.Ip "\(bu How do I start a process in the background?" 9
.Ip "\(bu How do I trap control characters/signals?" 9
.Ip "\(bu How do I modify the shadow password file on a Unix system?" 9
.Ip "\(bu How do I set the time and date?" 9
.Ip "\(bu How can I sleep() or alarm() for under a second?" 9
.Ip "\(bu How can I measure time under a second?" 9
.Ip "\(bu How can I do an atexit() or setjmp()/longjmp()? (Exception handling)" 9
.Ip "\(bu Why doesn't my sockets program work under System V (Solaris)? What does the error message \*(N"Protocol not supported\*(T" mean?" 9
.Ip "\(bu How can I call my system's unique C functions from Perl?" 9
.Ip "\(bu Where do I get the include files to do ioctl() or syscall()?" 9
.Ip "\(bu Why do setuid perl scripts complain about kernel problems?" 9
.Ip "\(bu How can I open a pipe both to and from a command?" 9
.Ip "\(bu Why can't I get the output of a command with system()?" 9
.Ip "\(bu How can I capture \s-1STDERR\s0 from an external command?" 9
.Ip "\(bu Why doesn't open() return an error when a pipe open fails?" 9
.Ip "\(bu What's wrong with using backticks in a void context?" 9
.Ip "\(bu How can I call backticks without shell processing?" 9
.Ip "\(bu Why can't my script read from \s-1STDIN\s0 after I gave it \s-1EOF\s0 (^D on Unix, ^Z on \s-1MS\s0\-\s-1DOS\s0)?" 9
.Ip "\(bu How can I convert my shell script to perl?" 9
.Ip "\(bu Can I use perl to run a telnet or ftp session?" 9
.Ip "\(bu How can I write expect in Perl?" 9
.Ip "\(bu Is there a way to hide perl's command line from programs such as \*(N"ps\*(T"?" 9
.Ip "\(bu I {changed directory, modified my environment} in a perl script.  How come the change disappeared when I exited the script?  How do I get my changes to be visible?" 9
.Ip "\(bu How do I close a process's filehandle without waiting for it to complete?" 9
.Ip "\(bu How do I fork a daemon process?" 9
.Ip "\(bu How do I make my program run with sh and csh?" 9
.Ip "\(bu How do I find out if I'm running interactively or not?" 9
.Ip "\(bu How do I timeout a slow event?" 9
.Ip "\(bu How do I set \s-1CPU\s0 limits?" 9
.Ip "\(bu How do I avoid zombies on a Unix system?" 9
.Ip "\(bu How do I use an \s-1SQL\s0 database?" 9
.Ip "\(bu How do I make a system() exit on control-C?" 9
.Ip "\(bu How do I open a file without blocking?" 9
.Ip "\(bu How do I install a \s-1CPAN\s0 module?" 9
.Ip "\(bu What's the difference between require and use?" 9
.Ip "\(bu How do I keep my own module/library directory?" 9
.Ip "\(bu How do I add the directory my program lives in to the module/library search path?" 9
.Ip "\(bu How do I add a directory to my include path at runtime?" 9
.Ip "\(bu What is socket.ph and where do I get it?" 9
.Ip "the \fIperlfaq9\fR manpage: Networking" 5
Networking, the Internet, and a few on the web.
.Ip "\(bu My \s-1CGI\s0 script runs from the command line but not the browser.   (500 Server Error)" 9
.Ip "\(bu How can I get better error messages from a \s-1CGI\s0 program?" 9
.Ip "\(bu How do I remove \s-1HTML\s0 from a string?" 9
.Ip "\(bu How do I extract URLs?" 9
.Ip "\(bu How do I download a file from the user's machine?  How do I open a file on another machine?" 9
.Ip "\(bu How do I make a pop-up menu in \s-1HTML\s0?" 9
.Ip "\(bu How do I fetch an \s-1HTML\s0 file?" 9
.Ip "\(bu How do I automate an \s-1HTML\s0 form submission?" 9
.Ip "\(bu How do I decode or create those %\-encodings on the web?" 9
.Ip "\(bu How do I redirect to another page?" 9
.Ip "\(bu How do I put a password on my web pages?" 9
.Ip "\(bu How do I edit my .htpasswd and .htgroup files with Perl?" 9
.Ip "\(bu How do I make sure users can't enter values into a form that cause my \s-1CGI\s0 script to do bad things?" 9
.Ip "\(bu How do I parse a mail header?" 9
.Ip "\(bu How do I decode a \s-1CGI\s0 form?" 9
.Ip "\(bu How do I check a valid mail address?" 9
.Ip "\(bu How do I decode a \s-1MIME/BASE64\s0 string?" 9
.Ip "\(bu How do I return the user's mail address?" 9
.Ip "\(bu How do I send mail?" 9
.Ip "\(bu How do I read mail?" 9
.Ip "\(bu How do I find out my hostname/domainname/\s-1IP\s0 address?" 9
.Ip "\(bu How do I fetch a news article or the active newsgroups?" 9
.Ip "\(bu How do I fetch/put an \s-1FTP\s0 file?" 9
.Ip "\(bu How can I do \s-1RPC\s0 in Perl?" 9
.Sh "Where to get this document"
This document is posted regularly to comp.lang.perl.announce and
several other related newsgroups.  It is available in a variety of
formats from \s-1CPAN\s0 in the /\s-1CPAN/\s0doc/FAQs/\s-1FAQ\s0/ directory, or on the web
at http://www.perl.com/perl/faq/ .
.Sh "How to contribute to this document"
You may mail corrections, additions, and suggestions to
perlfaq-suggestions@perl.com .  This alias should not be 
used to \fIask\fR FAQs.  It's for fixing the current \s-1FAQ\s0.
Send questions to the comp.lang.perl.misc newsgroup.
.Sh "What will happen if you mail your Perl programming problems to the authors"
Your questions will probably go unread, unless they're suggestions of
new questions to add to the \s-1FAQ\s0, in which case they should have gone
to the perlfaq-suggestions@perl.com instead.
.PP
You should have read section 2 of this faq.  There you would have
learned that comp.lang.perl.misc is the appropriate place to go for
free advice.  If your question is really important and you require a
prompt and correct answer, you should hire a consultant.
.SH "Credits"
When I first began the Perl FAQ in the late 80s, I never realized it
would have grown to over a hundred pages, nor that Perl would ever become
so popular and widespread.  This document could not have been written
without the tremendous help provided by Larry Wall and the rest of the
Perl Porters.
.SH "Author and Copyright Information"
Copyright (c) 1997-1999 Tom Christiansen and Nathan Torkington.
All rights reserved.
.Sh "Bundled Distributions"
When included as part of the Standard Version of Perl, or as part of
its complete documentation whether printed or otherwise, this work
may be distributed only under the terms of Perl's Artistic License.
Any distribution of this file or derivatives thereof \fIoutside\fR
of that package require that special arrangements be made with
copyright holder.
.PP
Irrespective of its distribution, all code examples in these files
are hereby placed into the public domain.  You are permitted and
encouraged to use this code in your own programs for fun
or for profit as you see fit.  A simple comment in the code giving
credit would be courteous but is not required.
.Sh "Disclaimer"
This information is offered in good faith and in the hope that it may
be of use, but is not guaranteed to be correct, up to date, or suitable
for any particular purpose whatsoever.  The authors accept no liability
in respect of this information or its use.
.SH "Changes"
.Ip "7/January/99" 4
Small touchups here and there.  Added all questions in this 
document as a sort of table of contents.
.Ip "22/June/98" 4
Significant changes throughout in preparation for the 5.005
release.
.Ip "24/April/97" 4
Style and whitespace changes from Chip, new question on reading one
character at a time from a terminal using \s-1POSIX\s0 from Tom.
.Ip "23/April/97" 4
Added http://www.oasis.leo.org/perl/ to the \fIperlfaq2\fR manpage.  Style fix to
the \fIperlfaq3\fR manpage.  Added floating point precision, fixed complex number
arithmetic, cross-references, caveat for Text::Wrap, alternative
answer for initial capitalizing, fixed incorrect regexp, added example
of Tie::IxHash to the \fIperlfaq4\fR manpage.  Added example of passing and storing
filehandles, added commify to the \fIperlfaq5\fR manpage.  Restored variable suicide,
and added mass commenting to the \fIperlfaq7\fR manpage.  Added Net::Telnet, fixed
backticks, added reader/writer pair to telnet question, added FindBin,
grouped module questions together in the \fIperlfaq8\fR manpage.  Expanded caveats
for the simple \s-1URL\s0 extractor, gave \s-1LWP\s0 example, added \s-1CGI\s0 security
question, expanded on the mail address answer in the \fIperlfaq9\fR manpage.
.Ip "25/March/97" 4
Added more info to the binary distribution section of the \fIperlfaq2\fR manpage.
Added Net::Telnet to the \fIperlfaq6\fR manpage.  Fixed typos in the \fIperlfaq8\fR manpage.  Added
mail sending example to the \fIperlfaq9\fR manpage.  Added Merlyn's columns to
the \fIperlfaq2\fR manpage.
.Ip "18/March/97" 4
Added the \s-1DATE\s0 to the \s-1NAME\s0 section, indicating which sections have
changed.
.Sp
Mentioned \s-1SIGPIPE\s0 and the \fIperlipc\fR manpage in the forking open answer in
the \fIperlfaq8\fR manpage.
.Sp
Fixed description of a regular expression in the \fIperlfaq4\fR manpage.
.Ip "17/March/97 Version" 4
Various typos fixed throughout.
.Sp
Added new question on Perl \s-1BNF\s0 on the \fIperlfaq7\fR manpage.
.Ip "Initial Release: 11/March/97" 4
This is the initial release of version 3 of the \s-1FAQ\s0; consequently there
have been no changes since its initial release.

.rn }` ''
.IX Title "PERLFAQ 1"
.IX Name "perlfaq - frequently asked questions about Perl ($Date: 1999/01/08 05:54:52 $)"

.IX Header "NAME"

.IX Header "DESCRIPTION"

.IX Item "perlfaq: Structural overview of the \s-1FAQ\s0."

.IX Item "the \fIperlfaq1\fR manpage: General Questions About Perl"

.IX Item "\(bu What is Perl?"

.IX Item "\(bu Who supports Perl?  Who develops it?  Why is it free?"

.IX Item "\(bu Which version of Perl should I use?"

.IX Item "\(bu What are perl4 and perl5?"

.IX Item "\(bu What is perl6?"

.IX Item "\(bu How stable is Perl?"

.IX Item "\(bu Is Perl difficult to learn?"

.IX Item "\(bu How does Perl compare with other languages like Java, Python, \s-1REXX\s0, Scheme, or Tcl?"

.IX Item "\(bu Can I do [task] in Perl?"

.IX Item "\(bu When shouldn't I program in Perl?"

.IX Item "\(bu What's the difference between \*(N"perl\*(T" and \*(N"Perl\*(T"?"

.IX Item "\(bu Is it a Perl program or a Perl script?"

.IX Item "\(bu What is a \s-1JAPH\s0?"

.IX Item "\(bu Where can I get a list of Larry Wall witticisms?"

.IX Item "\(bu How can I convince my sysadmin/supervisor/employees to use version (5/5.005/Perl instead of some other language)?"

.IX Item "the \fIperlfaq2\fR manpage: Obtaining and Learning about Perl"

.IX Item "\(bu What machines support Perl?  Where do I get it?"

.IX Item "\(bu How can I get a binary version of Perl?"

.IX Item "\(bu I don't have a C compiler on my system.  How can I compile perl?"

.IX Item "\(bu I copied the Perl binary from one machine to another, but scripts don't work."

.IX Item "\(bu I grabbed the sources and tried to compile but gdbm/dynamic loading/malloc/linking/... failed.  How do I make it work?"

.IX Item "\(bu What modules and extensions are available for Perl?  What is \s-1CPAN\s0?  What does \s-1CPAN/\s0src/... mean?"

.IX Item "\(bu Is there an \s-1ISO\s0 or \s-1ANSI\s0 certified version of Perl?"

.IX Item "\(bu Where can I get information on Perl?"

.IX Item "\(bu What are the Perl newsgroups on \s-1USENET\s0?  Where do I post questions?"

.IX Item "\(bu Where should I post source code?"

.IX Item "\(bu Perl Books"

.IX Item "\(bu Perl in Magazines"

.IX Item "\(bu Perl on the Net: \s-1FTP\s0 and \s-1WWW\s0 Access"

.IX Item "\(bu What mailing lists are there for perl?"

.IX Item "\(bu Archives of comp.lang.perl.misc"

.IX Item "\(bu Where can I buy a commercial version of Perl?"

.IX Item "\(bu Where do I send bug reports?"

.IX Item "\(bu What is perl.com?  "

.IX Item "the \fIperlfaq3\fR manpage: Programming Tools"

.IX Item "\(bu How do I do (anything)?"

.IX Item "\(bu How can I use Perl interactively?"

.IX Item "\(bu Is there a Perl shell?"

.IX Item "\(bu How do I debug my Perl programs?"

.IX Item "\(bu How do I profile my Perl programs?"

.IX Item "\(bu How do I cross-reference my Perl programs?"

.IX Item "\(bu Is there a pretty-printer (formatter) for Perl?"

.IX Item "\(bu Is there a ctags for Perl?"

.IX Item "\(bu Is there an \s-1IDE\s0 or Windows Perl Editor?"

.IX Item "\(bu Where can I get Perl macros for vi?"

.IX Item "\(bu Where can I get perl-mode for emacs?"

.IX Item "\(bu How can I use curses with Perl?"

.IX Item "\(bu How can I use X or Tk with Perl?"

.IX Item "\(bu How can I generate simple menus without using \s-1CGI\s0 or Tk?"

.IX Item "\(bu What is undump?"

.IX Item "\(bu How can I make my Perl program run faster?"

.IX Item "\(bu How can I make my Perl program take less memory?"

.IX Item "\(bu Is it unsafe to return a pointer to local data?"

.IX Item "\(bu How can I free an array or hash so my program shrinks?"

.IX Item "\(bu How can I make my \s-1CGI\s0 script more efficient?"

.IX Item "\(bu How can I hide the source for my Perl program?"

.IX Item "\(bu How can I compile my Perl program into byte code or C?"

.IX Item "\(bu How can I compile Perl into Java?"

.IX Item "\(bu How can I get \f(CW#!perl\fR to work on [\s-1MS\s0\-\s-1DOS\s0,\s-1NT\s0,...]?"

.IX Item "\(bu Can I write useful perl programs on the command line?"

.IX Item "\(bu Why don't perl one-liners work on my \s-1DOS/\s0Mac/\s-1VMS\s0 system?"

.IX Item "\(bu Where can I learn about \s-1CGI\s0 or Web programming in Perl?"

.IX Item "\(bu Where can I learn about object-oriented Perl programming?"

.IX Item "\(bu Where can I learn about linking C with Perl? [h2xs, xsubpp]"

.IX Item "\(bu I've read perlembed, perlguts, etc., but I can't embed perl in my C program, what am I doing wrong?"

.IX Item "\(bu When I tried to run my script, I got this message. What does it mean?"

.IX Item "\(bu What's MakeMaker?"

.IX Item "the \fIperlfaq4\fR manpage: Data Manipulation"

.IX Item "\(bu Why am I getting long decimals (eg, 19.9499999999999) instead of the numbers I should be getting (eg, 19.95)?"

.IX Item "\(bu Why isn't my octal data interpreted correctly?"

.IX Item "\(bu Does Perl have a round() function?  What about ceil() and floor()?  Trig functions?"

.IX Item "\(bu How do I convert bits into ints?"

.IX Item "\(bu Why doesn't & work the way I want it to?"

.IX Item "\(bu How do I multiply matrices?"

.IX Item "\(bu How do I perform an operation on a series of integers?"

.IX Item "\(bu How can I output Roman numerals?"

.IX Item "\(bu Why aren't my random numbers random?"

.IX Item "\(bu How do I find the week-of-the-year/day-of-the-year?"

.IX Item "\(bu How can I compare two dates and find the difference?"

.IX Item "\(bu How can I take a string and turn it into epoch seconds?"

.IX Item "\(bu How can I find the Julian Day?"

.IX Item "\(bu How do I find yesterday's date?"

.IX Item "\(bu Does Perl have a year 2000 problem?  Is Perl Y2K compliant?"

.IX Item "\(bu How do I validate input?"

.IX Item "\(bu How do I unescape a string?"

.IX Item "\(bu How do I remove consecutive pairs of characters?"

.IX Item "\(bu How do I expand function calls in a string?"

.IX Item "\(bu How do I find matching/nesting anything?"

.IX Item "\(bu How do I reverse a string?"

.IX Item "\(bu How do I expand tabs in a string?"

.IX Item "\(bu How do I reformat a paragraph?"

.IX Item "\(bu How can I access/change the first N letters of a string?"

.IX Item "\(bu How do I change the Nth occurrence of something?"

.IX Item "\(bu How can I count the number of occurrences of a substring within a string?"

.IX Item "\(bu How do I capitalize all the words on one line?"

.IX Item "\(bu How can I split a [character] delimited string except when inside [character]? (Comma-separated files)"

.IX Item "\(bu How do I strip blank space from the beginning/end of a string?"

.IX Item "\(bu How do I pad a string with blanks or pad a number with zeroes?"

.IX Item "\(bu How do I extract selected columns from a string?"

.IX Item "\(bu How do I find the soundex value of a string?"

.IX Item "\(bu How can I expand variables in text strings?"

.IX Item "\(bu What's wrong with always quoting \*(N"$vars\*(T"?"

.IX Item "\(bu Why don't my <<\s-1HERE\s0 documents work?"

.IX Item "\(bu What is the difference between a list and an array?"

.IX Item "\(bu What is the difference between $array[1] and @array[1]?"

.IX Item "\(bu How can I extract just the unique elements of an array?"

.IX Item "\(bu How can I tell whether a list or array contains a certain element?"

.IX Item "\(bu How do I compute the difference of two arrays?  How do I compute the intersection of two arrays?"

.IX Item "\(bu How do I test whether two arrays or hashes are equal?"

.IX Item "\(bu How do I find the first array element for which a condition is true?"

.IX Item "\(bu How do I handle linked lists?"

.IX Item "\(bu How do I handle circular lists?"

.IX Item "\(bu How do I shuffle an array randomly?"

.IX Item "\(bu How do I process/modify each element of an array?"

.IX Item "\(bu How do I select a random element from an array?"

.IX Item "\(bu How do I permute N elements of a list?"

.IX Item "\(bu How do I sort an array by (anything)?"

.IX Item "\(bu How do I manipulate arrays of bits?"

.IX Item "\(bu Why does defined() return true on empty arrays and hashes?"

.IX Item "\(bu How do I process an entire hash?"

.IX Item "\(bu What happens if I add or remove keys from a hash while iterating over it?"

.IX Item "\(bu How do I look up a hash element by value?"

.IX Item "\(bu How can I know how many entries are in a hash?"

.IX Item "\(bu How do I sort a hash (optionally by value instead of key)?"

.IX Item "\(bu How can I always keep my hash sorted?"

.IX Item "\(bu What's the difference between \*(N"delete\*(T" and \*(N"undef\*(T" with hashes?"

.IX Item "\(bu Why don't my tied hashes make the defined/exists distinction?"

.IX Item "\(bu How do I reset an each() operation part-way through?"

.IX Item "\(bu How can I get the unique keys from two hashes?"

.IX Item "\(bu How can I store a multidimensional array in a \s-1DBM\s0 file?"

.IX Item "\(bu How can I make my hash remember the order I put elements into it?"

.IX Item "\(bu Why does passing a subroutine an undefined element in a hash create it?"

.IX Item "\(bu How can I make the Perl equivalent of a C structure/\*(C+ class/hash or array of hashes or arrays?"

.IX Item "\(bu How can I use a reference as a hash key?"

.IX Item "\(bu How do I handle binary data correctly?"

.IX Item "\(bu How do I determine whether a scalar is a number/whole/integer/float?"

.IX Item "\(bu How do I keep persistent data across program calls?"

.IX Item "\(bu How do I print out or copy a recursive data structure?"

.IX Item "\(bu How do I define methods for every class/object?"

.IX Item "\(bu How do I verify a credit card checksum?"

.IX Item "\(bu How do I pack arrays of doubles or floats for \s-1XS\s0 code?"

.IX Item "the \fIperlfaq5\fR manpage: Files and Formats"

.IX Item "\(bu How do I flush/unbuffer an output filehandle?  Why must I do this?"

.IX Item "\(bu How do I change one line in a file/delete a line in a file/insert a line in the middle of a file/append to the beginning of a file?"

.IX Item "\(bu How do I count the number of lines in a file?"

.IX Item "\(bu How do I make a temporary file name?"

.IX Item "\(bu How can I manipulate fixed-record-length files?"

.IX Item "\(bu How can I make a filehandle local to a subroutine?  How do I pass filehandles between subroutines?  How do I make an array of filehandles?"

.IX Item "\(bu How can I use a filehandle indirectly?"

.IX Item "\(bu How can I set up a footer format to be used with write()?"

.IX Item "\(bu How can I write() into a string?"

.IX Item "\(bu How can I output my numbers with commas added?"

.IX Item "\(bu How can I translate tildes (~) in a filename?"

.IX Item "\(bu How come when I open a file read-write it wipes it out?"

.IX Item "\(bu Why do I sometimes get an \*(N"Argument list too long\*(T" when I use <*>?"

.IX Item "\(bu Is there a leak/bug in glob()?"

.IX Item "\(bu How can I open a file with a leading \*(N">\*(T" or trailing blanks?"

.IX Item "\(bu How can I reliably rename a file?"

.IX Item "\(bu How can I lock a file?"

.IX Item "\(bu Why can't I just open(\s-1FH\s0, \*(N">file.lock"")?"

.IX Item "\(bu I still don't get locking.  I just want to increment the number in the file.  How can I do this?"

.IX Item "\(bu How do I randomly update a binary file?"

.IX Item "\(bu How do I get a file's timestamp in perl?"

.IX Item "\(bu How do I set a file's timestamp in perl?"

.IX Item "\(bu How do I print to more than one file at once?"

.IX Item "\(bu How can I read in a file by paragraphs?"

.IX Item "\(bu How can I read a single character from a file?  From the keyboard?"

.IX Item "\(bu How can I tell whether there's a character waiting on a filehandle?"

.IX Item "\(bu How do I do a \f(CWtail -f\fR in perl?"

.IX Item "\(bu How do I dup() a filehandle in Perl?"

.IX Item "\(bu How do I close a file descriptor by number?"

.IX Item "\(bu Why can't I use \*(N"C:\etemp\efoo\*(T" in \s-1DOS\s0 paths?  What doesn't `C:\etemp\efoo.exe` work?"

.IX Item "\(bu Why doesn't glob'*.*' get all the files?"

.IX Item "\(bu Why does Perl let me delete read-only files?  Why does \f(CW-i\fR clobber protected files?  Isn't this a bug in Perl?"

.IX Item "\(bu How do I select a random line from a file?"

.IX Item "\(bu Why do I get weird spaces when I print an array of lines?"

.IX Item "the \fIperlfaq6\fR manpage: Regexps"

.IX Item "\(bu How can I hope to use regular expressions without creating illegible and unmaintainable code?"

.IX Item "\(bu I'm having trouble matching over more than one line.  What's wrong?"

.IX Item "\(bu How can I pull out lines between two patterns that are themselves on different lines?"

.IX Item "\(bu I put a regular expression into $/ but it didn't work. What's wrong?"

.IX Item "\(bu How do I substitute case insensitively on the \s-1LHS\s0, but preserving case on the \s-1RHS\s0?"

.IX Item "\(bu How can I make \f(CW\ew\fR match national character sets?"

.IX Item "\(bu How can I match a locale-smart version of \f(CW/[a-zA-Z]/\fR?"

.IX Item "\(bu How can I quote a variable to use in a regexp?"

.IX Item "\(bu What is \f(CW/o\fR really for?"

.IX Item "\(bu How do I use a regular expression to strip C style comments from a file?"

.IX Item "\(bu Can I use Perl regular expressions to match balanced text?"

.IX Item "\(bu What does it mean that regexps are greedy?  How can I get around it?"

.IX Item "\(bu How do I process each word on each line?"

.IX Item "\(bu How can I print out a word-frequency or line-frequency summary?"

.IX Item "\(bu How can I do approximate matching?"

.IX Item "\(bu How do I efficiently match many regular expressions at once?"

.IX Item "\(bu Why don't word-boundary searches with \f(CW\eb\fR work for me?"

.IX Item "\(bu Why does using $&, $`, or $\*(T' slow my program down?"

.IX Item "\(bu What good is \f(CW\eG\fR in a regular expression?"

.IX Item "\(bu Are Perl regexps DFAs or NFAs?  Are they \s-1POSIX\s0 compliant?"

.IX Item "\(bu What's wrong with using grep or map in a void context?"

.IX Item "\(bu How can I match strings with multibyte characters?"

.IX Item "\(bu How do I match a pattern that is supplied by the user?"

.IX Item "the \fIperlfaq7\fR manpage: General Perl Language Issues"

.IX Item "\(bu Can I get a \s-1BNF/\s0yacc/\s-1RE\s0 for the Perl language?"

.IX Item "\(bu What are all these $@%* punctuation signs, and how do I know when to use them?"

.IX Item "\(bu Do I always/never have to quote my strings or use semicolons and commas?"

.IX Item "\(bu How do I skip some return values?"

.IX Item "\(bu How do I temporarily block warnings?"

.IX Item "\(bu What's an extension?"

.IX Item "\(bu Why do Perl operators have different precedence than C operators?"

.IX Item "\(bu How do I declare/create a structure?"

.IX Item "\(bu How do I create a module?"

.IX Item "\(bu How do I create a class?"

.IX Item "\(bu How can I tell if a variable is tainted?"

.IX Item "\(bu What's a closure?"

.IX Item "\(bu What is variable suicide and how can I prevent it?"

.IX Item "\(bu How can I pass/return a {Function, FileHandle, Array, Hash, Method, Regexp}?"

.IX Item "\(bu How do I create a static variable?"

.IX Item "\(bu What's the difference between dynamic and lexical (static) scoping?  Between local() and my()?"

.IX Item "\(bu How can I access a dynamic variable while a similarly named lexical is in scope?"

.IX Item "\(bu What's the difference between deep and shallow binding?"

.IX Item "\(bu Why doesn't \*(N"my($foo) = <\s-1FILE\s0>;\*(T" work right?"

.IX Item "\(bu How do I redefine a builtin function, operator, or method?"

.IX Item "\(bu What's the difference between calling a function as &foo and foo()?"

.IX Item "\(bu How do I create a switch or case statement?"

.IX Item "\(bu How can I catch accesses to undefined variables/functions/methods?"

.IX Item "\(bu Why can't a method included in this same file be found?"

.IX Item "\(bu How can I find out my current package?"

.IX Item "\(bu How can I comment out a large block of perl code?"

.IX Item "\(bu How do I clear a package?"

.IX Item "the \fIperlfaq8\fR manpage: System Interaction"

.IX Item "\(bu How do I find out which operating system I'm running under?"

.IX Item "\(bu How come exec() doesn't return?"

.IX Item "\(bu How do I do fancy stuff with the keyboard/screen/mouse?"

.IX Item "\(bu How do I print something out in color?"

.IX Item "\(bu How do I read just one key without waiting for a return key?"

.IX Item "\(bu How do I check whether input is ready on the keyboard?"

.IX Item "\(bu How do I clear the screen?"

.IX Item "\(bu How do I get the screen size?"

.IX Item "\(bu How do I ask the user for a password?"

.IX Item "\(bu How do I read and write the serial port?"

.IX Item "\(bu How do I decode encrypted password files?"

.IX Item "\(bu How do I start a process in the background?"

.IX Item "\(bu How do I trap control characters/signals?"

.IX Item "\(bu How do I modify the shadow password file on a Unix system?"

.IX Item "\(bu How do I set the time and date?"

.IX Item "\(bu How can I sleep() or alarm() for under a second?"

.IX Item "\(bu How can I measure time under a second?"

.IX Item "\(bu How can I do an atexit() or setjmp()/longjmp()? (Exception handling)"

.IX Item "\(bu Why doesn't my sockets program work under System V (Solaris)? What does the error message \*(N"Protocol not supported\*(T" mean?"

.IX Item "\(bu How can I call my system's unique C functions from Perl?"

.IX Item "\(bu Where do I get the include files to do ioctl() or syscall()?"

.IX Item "\(bu Why do setuid perl scripts complain about kernel problems?"

.IX Item "\(bu How can I open a pipe both to and from a command?"

.IX Item "\(bu Why can't I get the output of a command with system()?"

.IX Item "\(bu How can I capture \s-1STDERR\s0 from an external command?"

.IX Item "\(bu Why doesn't open() return an error when a pipe open fails?"

.IX Item "\(bu What's wrong with using backticks in a void context?"

.IX Item "\(bu How can I call backticks without shell processing?"

.IX Item "\(bu Why can't my script read from \s-1STDIN\s0 after I gave it \s-1EOF\s0 (^D on Unix, ^Z on \s-1MS\s0\-\s-1DOS\s0)?"

.IX Item "\(bu How can I convert my shell script to perl?"

.IX Item "\(bu Can I use perl to run a telnet or ftp session?"

.IX Item "\(bu How can I write expect in Perl?"

.IX Item "\(bu Is there a way to hide perl's command line from programs such as \*(N"ps\*(T"?"

.IX Item "\(bu I {changed directory, modified my environment} in a perl script.  How come the change disappeared when I exited the script?  How do I get my changes to be visible?"

.IX Item "\(bu How do I close a process's filehandle without waiting for it to complete?"

.IX Item "\(bu How do I fork a daemon process?"

.IX Item "\(bu How do I make my program run with sh and csh?"

.IX Item "\(bu How do I find out if I'm running interactively or not?"

.IX Item "\(bu How do I timeout a slow event?"

.IX Item "\(bu How do I set \s-1CPU\s0 limits?"

.IX Item "\(bu How do I avoid zombies on a Unix system?"

.IX Item "\(bu How do I use an \s-1SQL\s0 database?"

.IX Item "\(bu How do I make a system() exit on control-C?"

.IX Item "\(bu How do I open a file without blocking?"

.IX Item "\(bu How do I install a \s-1CPAN\s0 module?"

.IX Item "\(bu What's the difference between require and use?"

.IX Item "\(bu How do I keep my own module/library directory?"

.IX Item "\(bu How do I add the directory my program lives in to the module/library search path?"

.IX Item "\(bu How do I add a directory to my include path at runtime?"

.IX Item "\(bu What is socket.ph and where do I get it?"

.IX Item "the \fIperlfaq9\fR manpage: Networking"

.IX Item "\(bu My \s-1CGI\s0 script runs from the command line but not the browser.   (500 Server Error)"

.IX Item "\(bu How can I get better error messages from a \s-1CGI\s0 program?"

.IX Item "\(bu How do I remove \s-1HTML\s0 from a string?"

.IX Item "\(bu How do I extract URLs?"

.IX Item "\(bu How do I download a file from the user's machine?  How do I open a file on another machine?"

.IX Item "\(bu How do I make a pop-up menu in \s-1HTML\s0?"

.IX Item "\(bu How do I fetch an \s-1HTML\s0 file?"

.IX Item "\(bu How do I automate an \s-1HTML\s0 form submission?"

.IX Item "\(bu How do I decode or create those %\-encodings on the web?"

.IX Item "\(bu How do I redirect to another page?"

.IX Item "\(bu How do I put a password on my web pages?"

.IX Item "\(bu How do I edit my .htpasswd and .htgroup files with Perl?"

.IX Item "\(bu How do I make sure users can't enter values into a form that cause my \s-1CGI\s0 script to do bad things?"

.IX Item "\(bu How do I parse a mail header?"

.IX Item "\(bu How do I decode a \s-1CGI\s0 form?"

.IX Item "\(bu How do I check a valid mail address?"

.IX Item "\(bu How do I decode a \s-1MIME/BASE64\s0 string?"

.IX Item "\(bu How do I return the user's mail address?"

.IX Item "\(bu How do I send mail?"

.IX Item "\(bu How do I read mail?"

.IX Item "\(bu How do I find out my hostname/domainname/\s-1IP\s0 address?"

.IX Item "\(bu How do I fetch a news article or the active newsgroups?"

.IX Item "\(bu How do I fetch/put an \s-1FTP\s0 file?"

.IX Item "\(bu How can I do \s-1RPC\s0 in Perl?"

.IX Subsection "Where to get this document"

.IX Subsection "How to contribute to this document"

.IX Subsection "What will happen if you mail your Perl programming problems to the authors"

.IX Header "Credits"

.IX Header "Author and Copyright Information"

.IX Subsection "Bundled Distributions"

.IX Subsection "Disclaimer"

.IX Header "Changes"

.IX Item "7/January/99"

.IX Item "22/June/98"

.IX Item "24/April/97"

.IX Item "23/April/97"

.IX Item "25/March/97"

.IX Item "18/March/97"

.IX Item "17/March/97 Version"

.IX Item "Initial Release: 11/March/97"

